import {
  blue,
  green,
  grey,
  lightBlue,
  purple,
  yellow,
} from "@material-ui/core/colors";

export const skillData = [
  {
    color: yellow[600],
    hover: yellow[400],
    text: "JavaScript",
    textColor: "#000",
    imgSrc: `/javascript.png`,
    alt: "JavaScript logo",
  },
  {
    color: blue[900],
    hover: blue[800],
    text: "React.js",
    textColor: "#fff",
    imgSrc: `/react.svg`,
    alt: "React.js logo",
  },
  {
    color: green[900],
    hover: green[800],
    text: "Node.js",
    textColor: "#fff",
    imgSrc: `/node.svg`,
    alt: "Node.js logo",
  },
  {
    color: purple[500],
    hover: purple[400],
    text: `Gatsby.js`,
    textColor: "#fff",
    imgSrc: `/gatsby.svg`,
    alt: "Gatsby.js logo",
  },
  {
    color: grey[400],
    hover: grey[200],
    text: "Next.js",
    textColor: "#000",
    imgSrc: `/next.svg`,
    alt: "Next.js logo",
  },
  {
    color: "#fff",
    hover: grey[400],
    text: "Git",
    textColor: "#000",
    imgSrc: `/git.png`,
    alt: "Git logo",
  },
  {
    color: green[400],
    hover: green[300],
    text: "MongoDB",
    textColor: "#000",
    imgSrc: `/mongo.png`,
    alt: "MongoDB logo",
  },
  {
    color: lightBlue[900],
    hover: lightBlue[800],
    text: "PostgreSQL",
    textColor: "#fff",
    imgSrc: `/postgresql.svg`,
    alt: "PostgreSQL logo",
  },
  {
    color: "#fff",
    hover: grey[400],
    text: "Linux",
    textColor: "#000",
    imgSrc: `/tux.svg`,
    alt: "Linux logo",
  },
];
